services:
  backend:
    build: .
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    environment:
      - PORT=3000
      - MONGO_URI
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET
      - JWT_SECRET
      - MAIL_USER
      - MAIL_PASS
      - MAIL_FROM_NAME
      - MAIL_FROM_EMAIL
      - CLOUDFLARE_TUNNEL_TOKEN_PROD
      - CLOUDFLARE_TUNNEL_TOKEN_STAGING
      - MOMO_PARTNER_CODE
      - MOMO_ACCESS_KEY
      - MOMO_SECRET_KEY
      - MOMO_CREATE_ENDPOINT
      - MOMO_REDIRECT_URL
      - MOMO_IPN_URL
      - ZP_APP_ID
      - ZP_KEY1
      - ZP_KEY2
      - ZP_API_BASE
      - ZP_REDIRECT_URL
      - ZP_CALLBACK_URL
      - STRIPE_SECRET
      - STRIPE_PRICE_ID
      - STRIPE_WEBHOOK_SECRET
      - BASE_URL
      - FIREBASE_SERVICE_ACCOUNT
      - GOOGLE_MAPS_API_KEY
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    depends_on:
      - nginx
    restart: unless-stopped

