tunnel: 679f7dbf-5527-49c5-aa9b-b5cb25d06361
credentials-file: /home/wsladmin/.cloudflared/679f7dbf-5527-49c5-aa9b-b5cb25d06361.json

ingress:
  - hostname: photel.io.vn
    service: http://nginx:80
  - service: http_status:404

originRequest:
  noTLSVerify: true
  httpHostHeader: localhost
